[package]
name = "blackjack_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blackjack_lib = {path = "../blackjack_lib"}
lazy_static = "1.4.0"
